### ISSUE TITLE
[Grumphp] Configuration spécifique non prise en charge

### ISSUE THREAD

**Issue by heristop** [assurance-maladie-digital/qualytou#6]
Etant donné un projet possédant une configuration custom de phpmd, c'est toujours la configuration standard qui est utilisée.

Reproductible en ajoutant une config custom à la racine d'un projet (ajoutant des exception par exemple), puis en l'appelant directement dans la config grumphp : 

```
       phpmd:
            ruleset: ['/pmd-ruleset-ma-config-custom.xml']
```

Les exceptions ne sont pas détectées et ne passent pas le test de qualité alors qu'en lançant à la main, le test passe : 

`$ phpmd src text ./pmd-ruleset-ma-config-custom.xml`

**Comment by roukmoute** [comment]
Cela vient du fait que la whitelist de grumphp pour phpmd est un tableau vide par défaut, donc il prend tous les dossiers et non plus juste le dossier `src`.

Cela donnerait plus quelque chose comme : 

 ```
./vendor/bin/phpmd features,src,tests text pmd-ruleset.xml
```
